services:
  bot:
    build:
      context: .
      dockerfile: DockerFile
    container_name: OneMessageBot

    env_file:
      - .env

    volumes:
      - ./.logs:/bot/.logs
      - ./video.mov:/bot/video.mov
      - .:/bot

    command: python3.13 -u main.py

    restart: unless-stopped