FROM python:3.13-slim AS builder

WORKDIR /app

COPY requirements.txt .

RUN --mount=type=cache,target=/root/.cache/pip \
    pip3.13 install --no-cache-dir -r requirements.txt

FROM python:3.13-slim

WORKDIR /app
 
COPY --from=builder /usr/local/lib/python3.13/site-packages /usr/local/lib/python3.13/site-packages

COPY . .

RUN rm -rf /root/.cache
